version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: open_queri
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: my-redis
    restart: unless-stopped
    ports:
      - "6379:5432"

networks:
  default:
    name: openqueri_net